default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
synthwave: styles/synthwave.scss
chillstep: styles/chillstep.scss
demogorgon: styles/demogorgon.scss